version: 2

sphinx:
  configuration: docs/conf.py

formats:
  - pdf
  - htmlzip   # RTD requires HTML output

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Upgrade pip/setuptools and install requirements
    - python -m pip install --upgrade pip setuptools
    - pip install -r docs/requirements.txt
    # Build HTML (required by RTD)
    - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html
    # Build PDF using Rinoh (no LaTeX needed)
    - sphinx-build -b rinoh docs/ $READTHEDOCS_OUTPUT/pdf
