# .readthedocs.yaml
version: 2

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Only build PDF
formats:
  - pdf

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Upgrade pip and setuptools
    - python -m pip install --upgrade pip setuptools
    # Install requirements
    - pip install -r docs/requirements.txt
