# .readthedocs.yaml
version: 2

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Build formats
formats:
  - pdf
  - htmlzip  # Must include HTML for RTD to be happy

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    - python -m pip install --upgrade pip setuptools
    - pip install -r docs/requirements.txt
