version: 2
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.14"
python:
  install:
    - requirements: docs/requirements.txt
sphinx:
  configuration: docs/conf.py
formats:
  - htmlzip  # builds standard HTML
  - pdf      # builds PDF
  - epub     # builds EPUB

