# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

  jobs:
    pre_install:
      - pip install --upgrade pip setuptools wheel
      - pip install sphinx==8.2.3 sphinx_rtd_theme>=2.0.0 wheel
    post_build:
      - echo "AuraOS build completed successfully."

python:
  install:
    - requirements: docs/requirements.txt

sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

# Optional additional downloadable output formats.
formats:
  - pdf
  - epub
