# .readthedocs.yaml
version: 2

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Only build PDF
formats:
  - pdf

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python:
      version: "3.12"
      install:
        - requirements: docs/requirements.txt
