version: 2

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Build formats
formats:
  - pdf
  - htmlzip   # HTML must be built, even if you don’t want it

# Build configuration
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  commands:
    # Upgrade pip and setuptools
    - python -m pip install --upgrade pip setuptools
    # Install requirements
    - pip install -r docs/requirements.txt
    # Build HTML (needed for RTD)
    - sphinx-build -b html docs/ $READTHEDOCS_OUTPUT/html
    # Build PDF
    - sphinx-build -b latex docs/ _build/latex
    - latexmk -r _build/latex/latexmkrc -pdf -f -dvi- -ps- -jobname=auraos -interaction=nonstopmode -outdir=$READTHEDOCS_OUTPUT/pdf _build/latex/*.tex
